import type { MetaFunction } from "react-router";
import { IoArrowForwardOutline } from "react-icons/io5";
import { DocsLayout } from "@/components/DocsLayout";
import { CodeBlock } from "@/components/CodeBlock";
import { withPageMeta } from "@/lib/seo";

export const meta: MetaFunction = () => {
  return withPageMeta("/api/props", [
    { title: "Props API - Uplofile" },
    {
      name: "description",
      content:
        "Complete reference for all props available in Uplofile components.",
    },
  ]);
};

const itemType = `type UploadFileItem<TMeta = any, TFileSource = unknown> = {
  uid: string;          // generated by Uplofile, the React key
  id?: string;          // yours, returned from upload()
  name: string;
  url?: string;         // set once the upload resolves
  previewUrl?: string;  // object URL locally, remote URL after
  file?: TFileSource;   // undefined for pre-hydrated files
  status: UploadStatus;
  progress?: number;    // 0–100, only while uploading
  error?: string;
  meta?: TMeta;         // anything you attach in beforeUpload
};`;

const resultType = `// what your upload() must resolve with
type UploadResult<TMeta = any> = {
  url: string;
  id?: string;
  meta?: TMeta;
  previewUrl?: string;
};`;

const statuses: [string, string][] = [
  ["idle", "Selected and waiting for upload to start"],
  ["uploading", "In flight. progress is populated if you call setProgress"],
  ["done", "url is now set"],
  [
    "error",
    "upload() rejected, or beforeUpload returned an invalid result with a reason",
  ],
  ["canceled", "Aborted via the signal; it no longer counts toward maxCount"],
  ["removing", 'Only under removeMode="strict", waiting on the server'],
];

const ApiProps = () => {
  return (
    <DocsLayout>
      <article className="doc-article types-article">
        <h1>Types</h1>
        <p className="doc-lead">
          The core data shapes exchanged between your upload function and custom
          UI.
        </p>

        <section id="item">
          <h2>UploadFileItem</h2>
          <CodeBlock code={itemType} filename="uplofile/types.ts" />
        </section>

        <section id="status">
          <h2>UploadStatus</h2>
          <p>
            The item&rsquo;s whole lifecycle. Branch on this in a custom
            preview.
          </p>
          <div className="status-list">
            {statuses.map(([status, description]) => (
              <div key={status}>
                <code>&quot;{status}&quot;</code>
                <span>{description}</span>
              </div>
            ))}
          </div>
        </section>

        <section id="result">
          <h2>UploadResult</h2>
          <CodeBlock code={resultType} filename="uplofile/types.ts" />
        </section>

        <div className="doc-pagination">
          <a href="/components/hidden-input">
            <small>Previous</small>
            <span>HiddenInput</span>
          </a>
          <a href="/api/actions">
            <small>Next</small>
            <span>
              Actions <IoArrowForwardOutline size={14} />
            </span>
          </a>
        </div>
      </article>
    </DocsLayout>
  );
};

export default ApiProps;
