import { DocsLayout } from "@/components/DocsLayout";

const ApiProps = () => {
  return (
    <DocsLayout>
      <article className="prose prose-slate dark:prose-invert max-w-none">
        <h1 className="text-3xl font-bold mb-2">Props Reference</h1>
        <p className="text-lg text-muted-foreground mb-8">
          Complete reference for all component props.
        </p>

        <section className="space-y-4 mb-12">
          <h2 className="text-xl font-semibold border-b border-border pb-2">
            FileItem Type
          </h2>

          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-border">
                  <th className="text-left py-3 px-2 font-semibold">
                    Property
                  </th>
                  <th className="text-left py-3 px-2 font-semibold">Type</th>
                  <th className="text-left py-3 px-2 font-semibold">
                    Description
                  </th>
                </tr>
              </thead>
              <tbody className="text-muted-foreground">
                <tr className="border-b border-border">
                  <td className="py-3 px-2">
                    <code className="code-inline">uid</code>
                  </td>
                  <td className="py-3 px-2">string</td>
                  <td className="py-3 px-2">
                    Unique identifier generated by Uplofile
                  </td>
                </tr>
                <tr className="border-b border-border">
                  <td className="py-3 px-2">
                    <code className="code-inline">id</code>
                  </td>
                  <td className="py-3 px-2">string?</td>
                  <td className="py-3 px-2">Optional ID from your backend</td>
                </tr>
                <tr className="border-b border-border">
                  <td className="py-3 px-2">
                    <code className="code-inline">name</code>
                  </td>
                  <td className="py-3 px-2">string</td>
                  <td className="py-3 px-2">File name</td>
                </tr>
                <tr className="border-b border-border">
                  <td className="py-3 px-2">
                    <code className="code-inline">size</code>
                  </td>
                  <td className="py-3 px-2">number</td>
                  <td className="py-3 px-2">File size in bytes</td>
                </tr>
                <tr className="border-b border-border">
                  <td className="py-3 px-2">
                    <code className="code-inline">type</code>
                  </td>
                  <td className="py-3 px-2">string</td>
                  <td className="py-3 px-2">MIME type</td>
                </tr>
                <tr className="border-b border-border">
                  <td className="py-3 px-2">
                    <code className="code-inline">preview</code>
                  </td>
                  <td className="py-3 px-2">string?</td>
                  <td className="py-3 px-2">Object URL for image preview</td>
                </tr>
                <tr className="border-b border-border">
                  <td className="py-3 px-2">
                    <code className="code-inline">url</code>
                  </td>
                  <td className="py-3 px-2">string?</td>
                  <td className="py-3 px-2">
                    Remote URL for pre-hydrated files
                  </td>
                </tr>
                <tr className="border-b border-border">
                  <td className="py-3 px-2">
                    <code className="code-inline">file</code>
                  </td>
                  <td className="py-3 px-2">File?</td>
                  <td className="py-3 px-2">
                    The original File object (undefined for pre-hydrated)
                  </td>
                </tr>
                <tr className="border-b border-border">
                  <td className="py-3 px-2">
                    <code className="code-inline">status</code>
                  </td>
                  <td className="py-3 px-2">"pending" | "done" | "error"</td>
                  <td className="py-3 px-2">Upload status</td>
                </tr>
              </tbody>
            </table>
          </div>
        </section>
      </article>
    </DocsLayout>
  );
};

export default ApiProps;
