import { DocsLayout } from "@/components/DocsLayout";
import { CodeBlock } from "@/components/CodeBlock";
import code from "./Props.demo.tsx?raw";

const ApiProps = () => {
  return (
    <DocsLayout>
      <article className="prose prose-slate dark:prose-invert max-w-none">
        <h1 className="text-3xl font-bold mb-2">Props Reference</h1>
        <p className="text-lg text-muted-foreground mb-8">
          Complete reference for the core data types.
        </p>

        <section className="space-y-4 mb-12">
          <h2 className="text-xl font-semibold border-b border-border pb-2">
            UploadFileItem Type
          </h2>

          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-border">
                  <th className="text-left py-3 px-2 font-semibold">
                    Property
                  </th>
                  <th className="text-left py-3 px-2 font-semibold">Type</th>
                  <th className="text-left py-3 px-2 font-semibold">
                    Description
                  </th>
                </tr>
              </thead>
              <tbody className="text-muted-foreground">
                <tr className="border-b border-border">
                  <td className="py-3 px-2">
                    <code className="code-inline">uid</code>
                  </td>
                  <td className="py-3 px-2">string</td>
                  <td className="py-3 px-2">
                    Unique identifier generated by Uplofile
                  </td>
                </tr>
                <tr className="border-b border-border">
                  <td className="py-3 px-2">
                    <code className="code-inline">id</code>
                  </td>
                  <td className="py-3 px-2">string?</td>
                  <td className="py-3 px-2">Optional ID from your backend</td>
                </tr>
                <tr className="border-b border-border">
                  <td className="py-3 px-2">
                    <code className="code-inline">name</code>
                  </td>
                  <td className="py-3 px-2">string</td>
                  <td className="py-3 px-2">File name</td>
                </tr>
                <tr className="border-b border-border">
                  <td className="py-3 px-2">
                    <code className="code-inline">status</code>
                  </td>
                  <td className="py-3 px-2">UploadStatus</td>
                  <td className="py-3 px-2">
                    Current status: <code className="code-inline">"idle"</code>, <code className="code-inline">"uploading"</code>, <code className="code-inline">"done"</code>, <code className="code-inline">"error"</code>, <code className="code-inline">"canceled"</code>, <code className="code-inline">"removing"</code>
                  </td>
                </tr>
                <tr className="border-b border-border">
                  <td className="py-3 px-2">
                    <code className="code-inline">progress</code>
                  </td>
                  <td className="py-3 px-2">number?</td>
                  <td className="py-3 px-2">Upload progress (0-100)</td>
                </tr>
                <tr className="border-b border-border">
                  <td className="py-3 px-2">
                    <code className="code-inline">previewUrl</code>
                  </td>
                  <td className="py-3 px-2">string?</td>
                  <td className="py-3 px-2">URL for image preview (object URL or remote URL)</td>
                </tr>
                <tr className="border-b border-border">
                  <td className="py-3 px-2">
                    <code className="code-inline">url</code>
                  </td>
                  <td className="py-3 px-2">string?</td>
                  <td className="py-3 px-2">
                    Remote URL of the uploaded file
                  </td>
                </tr>
                <tr className="border-b border-border">
                  <td className="py-3 px-2">
                    <code className="code-inline">error</code>
                  </td>
                  <td className="py-3 px-2">string?</td>
                  <td className="py-3 px-2">Error message if upload fails</td>
                </tr>
                <tr className="border-b border-border">
                  <td className="py-3 px-2">
                    <code className="code-inline">file</code>
                  </td>
                  <td className="py-3 px-2">File?</td>
                  <td className="py-3 px-2">
                    The original File object (undefined for pre-hydrated files)
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold border-b border-border pb-2">
            Usage Example
          </h2>
          <CodeBlock code={code} language="tsx" />
        </section>
      </article>
    </DocsLayout>
  );
};

export default ApiProps;
